### ISSUE TITLE
使用aws Ubuntu Server 20.04 LTS (HVM), SSD Volume Type 安装失败

### ISSUE THREAD

**Issue by WangNeos** [crazypeace/v2ray#4]
22年12月时候安装成功，今天手贱把虚拟机内核玩坏了。只能重新创建，配置与原来相同。但是目前安装脚本到最后一步显示报错

..由于你的 VPS 内核支持开启 BBR ...已经为你启用 BBR 优化....

如果你的小鸡是双栈(同时有IPv4和IPv6的IP)，请选择你把v2ray搭在哪个'网口'上
如果你不懂这段话是什么意思, 请直接回车
Input 4 for IPv4, 6 for IPv6 [4/6]:
parse error: Invalid numeric literal at line 1, column 10

 检测本机IP失败, 请加群求助https://t.me/+ISuvkzFGZPBhMzE1

IP已经在aws中设置好，ssh也能连接，不知道是不是脚本更新的原因。之前的安装中从来没出现过这个问题

**Comment by WangNeos** [comment]
看了下脚本，好像跟myip.com有关系？

**Comment by crazypeace** [comment]
可能是检测IP的网站, 在你的VPS上访问出现问题.
我修改了一下脚本中检测IP的方法.
